services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sbc_api
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app
    environment:
      - FLASK_ENV=development